namespace Identity.Migration;

/// <summary>Tables replicated between the monolith and identitydb, in FK-safe insert order.</summary>
public static class SyncTables
{
    public static readonly (string Name, string[] Key)[] All =
    [
        ("AspNetRoles", ["Id"]),
        ("AspNetUsers", ["Id"]),
        ("AspNetRoleClaims", ["Id"]),
        ("AspNetUserClaims", ["Id"]),
        ("AspNetUserLogins", ["LoginProvider", "ProviderKey"]),
        ("AspNetUserRoles", ["UserId", "RoleId"]),
        ("AspNetUserTokens", ["UserId", "LoginProvider", "Name"]),
        ("OpenIddictApplications", ["Id"]),
        ("OpenIddictScopes", ["Id"]),
        ("OpenIddictAuthorizations", ["Id"]),
        ("OpenIddictTokens", ["Id"]),
    ];

    /// <summary>Columns that are IDENTITY in SQL Server / GENERATED BY DEFAULT in Postgres.</summary>
    public static readonly Dictionary<string, string> IdentityColumns = new()
    {
        ["AspNetRoleClaims"] = "Id",
        ["AspNetUserClaims"] = "Id",
    };
}
