# Kafka Connect with the Debezium SQL Server source and the Debezium JDBC sink connector.
FROM quay.io/debezium/connect:3.1

ARG DEBEZIUM_VERSION=3.1.3.Final
ARG POSTGRES_JDBC_VERSION=42.7.7
ARG MAVEN_REPO=https://repo1.maven.org/maven2

USER root
RUN cd /kafka/connect \
 && curl -fsSL "${MAVEN_REPO}/io/debezium/debezium-connector-jdbc/${DEBEZIUM_VERSION}/debezium-connector-jdbc-${DEBEZIUM_VERSION}-plugin.tar.gz" \
      | tar xz \
 && curl -fsSL -o /kafka/connect/debezium-connector-jdbc/postgresql-${POSTGRES_JDBC_VERSION}.jar \
      "${MAVEN_REPO}/org/postgresql/postgresql/${POSTGRES_JDBC_VERSION}/postgresql-${POSTGRES_JDBC_VERSION}.jar" \
 && chown -R kafka:kafka /kafka/connect
USER kafka
